[package]
name = "bis_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
strum_macros = "0.27.2"

[[bin]]
name = "convert"
path = "src/main.rs"

[[bin]]
name = "comparer"
path = "bin/comparer.rs"

